### ISSUE TITLE
I want to Create different shapes by this xy map Generator plz help

### ISSUE THREAD

**Issue by LedArts** [macetech/FastLED-XY-Map-Generator#2]
hello sir,

i am trying the xy map but not getting the write code

// Params for width and height
const uint8_t kMatrixWidth = 24;
const uint8_t kMatrixHeight = 8;

#define NUM_LEDS (kMatrixWidth * kMatrixHeight)
CRGB leds[ NUM_LEDS ];
#define LAST_VISIBLE_LED 121
uint8_t XY (uint8_t x, uint8_t y) {
  // any out of bounds address maps to the first hidden pixel
  if ( (x >= kMatrixWidth) || (y >= kMatrixHeight) ) {
    return (LAST_VISIBLE_LED + 1);
  }

  const uint8_t XYTable[] = {
   122, 126, 127, 132, 133, 138, 139, 144, 145, 150, 151, 156, 157, 162, 163, 168, 169, 174, 175, 180, 181, 186, 187, 191,
     0,  10,  11,  20,  21,  30,  31,  40,  41,  50,  51,  60,  61,  70,  71,  80,  81,  90,  91, 100, 101, 110, 111, 121,
     1, 125,  12,  19,  22, 137,  32,  39,  42,  49, 152,  59,  62,  69,  72, 167,  82,  89,  92,  99, 182, 109, 112, 120,
     2,   9, 128,  18, 134,  29, 140,  38,  43, 149,  52, 155,  63,  68, 164,  79, 170,  88,  93, 179, 102, 185, 113, 119,
     3,   8,  13, 131,  23,  28,  33, 143, 146,  48,  53,  58, 158, 161,  73,  78,  83, 173, 176,  98, 103, 108, 188, 118,
     4,   7,  14,  17,  24,  27,  34,  37,  44,  47,  54,  57,  64,  67,  74,  77,  84,  87,  94,  97, 104, 107, 114, 117,
     5,   6,  15,  16,  25,  26,  35,  36,  45,  46,  55,  56,  65,  66,  75,  76,  85,  86,  95,  96, 105, 106, 115, 116,
   123, 124, 129, 130, 135, 136, 141, 142, 147, 148, 153, 154, 159, 160, 165, 166, 171, 172, 177, 178, 183, 184, 189, 190
  };

  uint8_t i = (y * kMatrixWidth) + x;
  uint8_t j = XYTable[i];
  return j;
}

After this i want to Scrolling effect of this xy map plz give me rest of code by which i can scroll this xy map

**Comment by macegr** [comment]
LedArts, this utility ONLY provides a function to map an irregular matrix to an easy-to-use rectangular matrix. ALL OTHER graphics functions are up to the programmer to create. Check the [RGB Shades project](https://github.com/macetech/RGBShades) for examples of the XY map in use. Scrolling a rectangular matrix is easy, here is one example:
```
// Shift all pixels by one, right or left (0 or 1)
void scrollArray(byte scrollDir) {
  
    byte scrollX = 0;
    for (byte x = 1; x < kMatrixWidth; x++) {
      if (scrollDir == 0) {
        scrollX = kMatrixWidth - x;
      } else if (scrollDir == 1) {
        scrollX = x - 1;
      }
      
      for (byte y = 0; y < kMatrixHeight; y++) {
        leds[XY(scrollX,y)] = leds[XY(scrollX + scrollDir*2 - 1,y)];
      }
    }
}
```

**Comment by LedArts** [comment]
thank you so much sir,
sir i want only one example in which i want to create any shape like zig zag or  ladder shape  and want to scroll it. Can u give me any one example plz.
it will be more help full for me

**Comment by macegr** [comment]
I can't give the example, as I don't know anything about your application. Above, you can see the full routine for scrolling a matrix. Drawing a pixel on a matrix with x-y coordinates is the most basic of basic concepts for graphics programming; do that a number of times until the shape you want is drawn to the matrix. The RGB Shades project I linked above has many, many examples of drawing patterns to a matrix, including a full character set and text scrolling code.

**Comment by LedArts** [comment]
ok sir i will try and let u know
but if u have any example of drawing shape in matrix plz tell me.

**Comment by LedArts** [comment]
sir i try rgb shades program but its very complicated for me
i need simple program of 24x8 matrix array and want to scroll it 
and if possible to change the colors of led.
can u plz make one simple program for me
