### ISSUE TITLE
Extra feature

### ISSUE THREAD

**Issue by FLPLF** [macetech/FastLED-XY-Map-Generator#3]
Hi,
Loving your code.

Any chance of an update with a 'clear all LEDs' button to clear the matrix?
I have a 80x80 grid, and only need 91 LEDs highlighting.

Thanks,
Paul

**Comment by Intrinsically-Sublime** [comment]
If you change line 79 in XYmapper.js from
pixelarray[i][0] = "E";
to
pixelarray[i][0] = "D";
It will create the diagram with all of them disabled. It will still show the led icons but they will actually be inactive and you will have to click them to enable them.

**Comment by Intrinsically-Sublime** [comment]
I decided to dig a little deeper and it was relatively easy to implement a check box for starting with all pixels cleared. You can try it on my version but be aware it produces slightly different results and has extra options. https://intrinsically-sublime.github.io/FastLED-XY-Map-Generator/

**Comment by marmilicious** [comment]
@Intrinsically-Sublime  Nice updates.

**Comment by FLPLF** [comment]
Excellent :-)

Thank you

**Comment by macegr** [comment]
@Intrinsically-Sublime Very cool edits, thank you! I'm not used to coding user interfaces (or much heavyweight javascript) so definitely flattered you found it useful enough to modify and use.
